Melhorias no ValidationException
vindi/vindi-php pull request #18
Opened 2017-05-06 17:34 UTC by bissolli

Hoje o retorno das validações está dificultando demais a vida do desenvolvedor, apenas retornando uma mensagem simples que não passou da validação!

Fiz algumas melhorias na exibição dessas informações de forma que o desenvolvedor consiga encontrar onde está o problema!

E também adicionei uma variável de ambiente para retornar como json caso queiram.

2017-05-09 14:44 UTC, bissolli commented
@rscafi @asagalo rola dar uma olhada nessa PR? Vai ajudar bastante a galera debugar e encontrar os possíveis erros! Se precisarem de qualquer ajuste é só falar!

2017-10-02 18:55 UTC, lyoncesar commented
Boa tarde @bissolli, tudo bem?
Obrigado por enviar o PR.
Eu assumi a sdk recentemente e peço desculpas pela demora em respondermos.
Fiz a validação e aparentemente está ok, mas não tem testes.
Você consegue escrever os testes? Assim mantemos o padrão dela.

Abs.

2017-10-03 18:25 UTC, DNA requested changes
Gostei da abordagem, só faltou alguns ajustes e os testes :)

2017-10-03 18:25 UTC, DNA commented on README.md
> +putenv('VINDI_EXCEPTION_AS_JSON=true');
Aqui seria melhor usar `VINDI_EXCEPTION_OUTPUT` com os valores possíveis sendo "text" e "json", com "text" sendo o padrão.

2017-10-03 18:25 UTC, DNA commented on src/Exceptions/ValidationException.php
> +            return $errors;
Aqui seria interessante manter o padrão do json que o loop gera:
`return json_encode(['general' => $error])`

Dessa forma o programa que usará a api não precisará ficar testando o formato que ele recebe

2017-10-03 18:25 UTC, DNA commented on src/Exceptions/ValidationException.php
> +        return "Os seguintes erros de validação foram encontrados:" . $error_log;
Essa string pode ficar lá onde você definiu o `$error_log = '';`, assim a gente só precisa deixar um `return $error_log;` aqui :)

2017-10-03 18:25 UTC, DNA commented on src/Exceptions/ValidationException.php
> +        foreach ($errors as $error)
Os loops e ifs não estão de acordo com a PSR-2, rode o `phpcs` nesse arquivo para manter o código consistente

2017-10-04 05:26 UTC, bissolli commented
Boa, vou trabalhar nisso hoje, e subo as atualizações mais tarde!

2017-10-05 15:15 UTC, lyoncesar commented
@bissolli, tudo bem?
Nós estamos trabalhando em uma nova versão da SDK que está prevista para sair nas próximas duas semanas. Essa atualização vai incluir uma nova tratativa para o retorno de erros, o novo ambiente sandbox da Vindi e alguns endpoints da api que ainda não estão disponíveis na SDK.
Também vamos aproveitar para remover a variável de ambiente que é usada para enviar a chave api.
Peço desculpas pela demora que tivemos em revisar o seu PR, ele está dentro dos padrões da lib, mas com as alterações da nova versão isso também será resolvido.
Por esse motivo eu vou encerrar o PR por enquanto.
Se quiser saber mais detalhes da nova versão, inclusive se tiver sugestões, por favor me mande no lyon.oliveira@vindi.com.br.

Abs.

2017-10-05 15:15 UTC, closed without merging