adiciona novos metodos e endpoints da api
vindi/vindi-php pull request #20
Opened 2017-09-04 20:11 UTC by lyoncesar

Este PR adiciona os novos endpoints e métodos da API.

2017-09-04 22:15 UTC, DNA requested changes
Tirando o erro do teste parece que está tudo ok.
Há algumas classes com apenas a base criada, esse é o primeiro PR de uma série?

2017-09-04 22:15 UTC, DNA commented on tests/MerchantUserTest.php
> +{
Aqui deveria ser `MerchantUserTest`, não? Deve ser isso que está quebrando os testes

2017-09-11 13:58 UTC, wagner requested changes
@lyoncesar, é necessário corrigir os testes.

2017-09-28 22:48 UTC, wagner commented
@lyoncesar estou encerrando o PR por falta de feedback. Se acreditar que ainda é válido, crie um novo por favor.

2017-09-28 22:48 UTC, closed without merging