adiciona informação sobre utilização do sandbox
vindi/vindi-php pull request #23
Opened 2017-10-03 16:02 UTC by lyoncesar

Apenas adicionando informação sobre a utilização do sandbox no readme.

2017-10-03 18:07 UTC, DNA requested changes

2017-10-03 18:07 UTC, DNA commented on README.md
> +Vindi\Vindi::$apiBase = 'https://sandbox-app.vindi.com.br/api/v1/';
Não entendi o objetivo desse PR mencionar o `Vindi\Vindi::$apiBase` se temos o #21 que resolve esse problema. Podemos simplesmente efetuar o merge e soltar a versão 1.1 :thinking:

2017-10-03 18:24 UTC, lyoncesar commented
Fiz a menção dele no readme porque o Wagner comentou que não acha legal usarmos uma variável de ambiente para resolver isso. Como temos a opção de preencher a url usando o operador de resolução de escopo eu achei melhor documentar ele do que fazer alteração no código.

2017-10-03 18:24 UTC, lyoncesar commented on README.md
> +Vindi\Vindi::$apiBase = 'https://sandbox-app.vindi.com.br/api/v1/';
Fiz a menção dele no readme porque o Wagner comentou que não acha legal usarmos uma variável de ambiente para resolver isso. Como temos a opção de preencher a url usando o operador de resolução de escopo eu achei melhor documentar ele do que fazer alteração no código.

2017-10-03 18:36 UTC, DNA commented on README.md
> +Vindi\Vindi::$apiBase = 'https://sandbox-app.vindi.com.br/api/v1/';
Mesmo que a gente não use variáveis de ambiente, alterar a url dessa forma não é uma boa, pois quebra o encapsulamento. As duas URLs deveriam ser propriedades privadas e o sistema chama algum método para que seja feita a alteração da url internamente. Esse processo tem de ser transparente para quem usa a SDK

2017-10-05 19:00 UTC, lyoncesar commented
Estou encerrando esse PR para iniciar o desenvolvimento da nova versão da SDK com ajustes para o Sandbox, melhorias no response e remoção das variáveis de ambiente.

2017-10-05 19:00 UTC, closed without merging