Feature/modifica construtor resource
vindi/vindi-php pull request #40
Opened 2018-05-07 16:48 UTC by rtakauti

2018-05-07 17:02 UTC, wagner requested changes
Eu não consigo falar muito sobre o código PHP, mas a documentação precisa ficar mais clara sobre essa nova funcionalidade.

2018-05-07 17:02 UTC, wagner commented on .gitignore
> +.idea/
Esse é um arquivo do seu editor? Se for, é melhor colocar no `git config --global` em vez de adicionar no projeto.

2018-05-07 17:02 UTC, wagner commented on README.md
> +![alt text align:center](https://www.vindi.com.br/assets/images/logo-footer.png "Vindi")
A imagem não apareceu aqui.

2018-05-07 17:02 UTC, wagner commented on README.md
> +
Acredito que a documentação não está clara quanto às formas de autenticação.

Minha sugestão seria criar uma seção "Autenticação" explicando que preferencialmente a variável de ambiente será utilizada, ao menos que a chave seja explicitamente configurada na instância.

2018-05-07 17:02 UTC, wagner commented on src/Vindi.php
> +        if (!empty(getenv(static::$apiTimeOutEnvVar))) {
Esse código sobre timeout tem alguma relação com o PR?

2018-05-07 17:02 UTC, wagner commented on CHANGELOG.md
> +
Dúvida: Esse changelog mistura português e inglês por algum motivo específico? Ele é exibido em algum outro lugar?

2018-05-07 19:33 UTC, rtakauti commented on CHANGELOG.md
> +
O CHANGELOG.md está em inglês, para seguir com o padrão essa nova versão também deixei inglês

2018-05-07 19:54 UTC, rtakauti commented on README.md
> +![alt text align:center](https://www.vindi.com.br/assets/images/logo-footer.png "Vindi")
Foi uma escolha de imagem branca que não aparecia no fundo de mesma cor.

2018-05-07 22:05 UTC, carolina-y commented on README.md
> +    \Vindi\Vindi::VINDI_API_KEY => 'SUA_CHAVE_DA_API',
A pessoa não pode chamar via este código abaixo?

```
$arguments = array(
    'VINDI_API_KEY' => 'SUA_CHAVE_DA_API',
    'VINDI_API_URI' => 'https://sandbox-app.vindi.com.br/api/v1/'
);
```

(entendo a completude, mas é mais legível para humanos 'VINDI_API_KEY' e afins)

2018-05-07 22:07 UTC, carolina-y commented on src/Vindi.php
> -    public static $apiUriEnvVar = 'VINDI_API_URI';
:+1:

2018-05-08 20:58 UTC, lyoncesar commented on README.md
> +> Esse método de autenticação utiliza-se de inserção de um *array* como argumento na primeira instância de uma classe *filha* de Resource, sendo ignorada uma nova tentativa de inserir o argumento em
Será que tem como deixar em negrito essa parte do texto avisa sobre a inserção de um novo argumento em outra instância? Acho que isso pode sinalizar a importância do alerta para o cliente.

2018-05-08 21:09 UTC, carolina-y approved these changes

2018-05-08 21:49 UTC, lyoncesar commented on src/Vindi.php
> -    public static $apiUriEnvVar = 'VINDI_API_URI';
Também curti isso aqui :+1:

2018-05-08 21:49 UTC, lyoncesar approved these changes

2018-05-10 22:46 UTC, wagner commented on README.md
> +
O texto foi copiado e colado só mudando o método de autenticação? Não vai dar o dobro de trabalho pra atualizar depois?

Eu havia imaginado simplesmente criar uma seção "Autenticação" com os dois métodos.

2018-05-10 22:47 UTC, wagner approved these changes
Estou aprovando, mas acredito que a documentação poderia ser melhor, evitando a duplicação no exemplo e também incluindo alguma referência para os outros serviços ao invés de manter uma documentação paralela no Zendesk.

2018-05-11 21:58 UTC, lyoncesar approved these changes

2018-05-11 22:31 UTC, lyoncesar commented
Acho que está dentro da documentação atual, podemos levantar a documentação de todas as integrações para validar tudo e depois criarmos uma nova.

2018-05-11 22:33 UTC, carolina-y approved these changes

2018-05-11 22:34 UTC, merged