Adiciona endpoint de movements
vindi/vindi-php pull request #53
Opened 2019-07-03 00:31 UTC by victorsinged

## Motivação
A SDK em PHP não possui a chamada para utilizar a endpoint de movimentos financeiros.

## Solução Proposta
Adicionei o arquivo para essa chamada na API.

2019-07-03 11:26 UTC, laerte-guimaraes requested changes
O arquivo deve ficar dentro da pasta ['_src_'](https://github.com/vindi/vindi-php/tree/movements/src).

Quais serão os métodos implementados para utilização no _Movements_?
Qualquer dúvida, você pode se basear no endpoint [Bill](https://github.com/vindi/vindi-php/blob/master/src/Bill.php) :smiley: 

Seria interessante também inserir os testes, já que estamos tratando de um novo endpoint, o que acha? :thinking:

2019-07-03 15:11 UTC, carolina-y commented on tests/MovementTest.php
> +class movementTest extends ResourceTest
Pelo nome do arquivo, seria `MovementTest`?

2019-07-03 15:12 UTC, carolina-y commented on tests/MovementTest.php
> +    public function setUp()
Estamos usando aqui notação húngara pra função e no teste, underscores (it_should_have_an_endpoint). Ia notar, mas infelizmente é o padrão para todos os testes. Seria legal no futuro, se possível, padronizar em algum deles!

2019-07-03 18:44 UTC, laerte-guimaraes commented on tests/MovementTest.php
> +    public function setUp()
O ideal seria padronizar em "_camelcase_" todos os pontos em um próximo PR @victorsinged  :hear_no_evil:

2019-07-03 21:08 UTC, victorsinged commented on tests/MovementTest.php
> +    public function setUp()
É uma boa, pretendo subir um novo PR atualizando os arquivos da SDK para os métodos novos do PHP.

2019-07-04 12:11 UTC, victorsinged commented on tests/MovementTest.php
> +class movementTest extends ResourceTest
Arrumado!

2019-07-04 16:20 UTC, laerte-guimaraes approved these changes

2019-07-04 18:51 UTC, augustohub approved these changes

2019-07-04 18:58 UTC, merged