Adiciona endpoint para lotes de exportação
vindi/vindi-php pull request #56
Opened 2019-09-02 14:00 UTC by victorsinged

## Motivação
Recentemente, a API recebeu uma nova endpoint para a exportação de arquivos de remessa.

## Solução Proposta
Estou adicionando o arquivo `ExportBatch.php` para manter a SDK atualizada.

## Como testar

Fiz a criação de um cliente, de uma fatura utilizando o boleto online, um lote de exportação e em seguida o aprovei.
 
```php
<?php
$customerService = new Vindi\Customer($arguments);
$billService = new Vindi\Bill($arguments);
$exportbatchService = new Vindi\ExportBatch($arguments);
$cliente = $customerService->create([
  'name' => 'teste de remessa'
]);

echo $cliente->id.PHP_EOL;

$bill = $billService->create([
  'customer_id' => $cliente->id,
  'payment_method_code' => 'bank_slip',
  'bill_items' => [
      [
        'product_id' => 843,
        'amount' => 100
      ]
    ]
]);

echo $bill->id.PHP_EOL;

$loteExportacao = $exportbatchService->create([
  'payment_method_code' => 'bank_slip'
]);

$loteExportacao = $exportbatchService->approve($loteExportacao->id);
echo $loteExportacao->url.PHP_EOL;
```

Resultado:

![image](https://user-images.githubusercontent.com/50752933/64119609-a0d73380-cd70-11e9-9e27-4b95fb4f79b7.png)

2019-09-02 18:19 UTC, laerte-guimaraes requested changes

2019-09-02 18:19 UTC, laerte-guimaraes commented on src/ExportBatch.php
> +}
```suggestion
}

```

2019-09-02 18:19 UTC, laerte-guimaraes commented on tests/ExportBatchTest.php
> +}
```suggestion

```

2019-09-02 18:22 UTC, laerte-guimaraes commented on tests/ExportBatchTest.php
> +}
```suggestion
}

```

2019-09-02 18:25 UTC, laerte-guimaraes approved these changes

2019-09-02 20:44 UTC, laerte-guimaraes commented on tests/ExportBatchTest.php
> +
```suggestion

use stdClass;
```

2019-09-03 19:08 UTC, carolina-y approved these changes

2019-09-03 19:12 UTC, merged